### ISSUE TITLE
Large model detected - please remember setting and disable future dialog

### ISSUE THREAD

**Issue by fdwr** [lutzroeder/netron#1135]
## Please search existing issues to avoid creating duplicates.

Doesn't look like a duplicate of 68 or 178.

## Describe the feature you'd like.

Nearly every time I open a model nowadays (any recent customer models, popular models from huggingface...), I'm greeted with this dialog. Can I click `Yes` once just have Netron remember that? In the worst case, if loading took too long, I'd just click the X anyway. Thanks.

![image](https://github.com/lutzroeder/netron/assets/1809166/ac81cd4e-4b21-48d3-8cee-3f51f8ac062f)

This includes Stable Diffusion unet (8401 nodes) and safety checker (2923 nodes) and others I can't share. I'm unsure what the node threshold is, but models are getting bigger and bigger over time (LLM's) - it's not just squeezenet.onnx anymore 😉.

**Comment by lutzroeder** [comment]
@fdwr the dialog is by design. Users are often not aware of the size of the models loaded and the intuition that the app is hanging leads to bug reports which are difficult to tell apart from other bugs. There might be better UX ideas like showing an option to cancel the graph layout for large graphs after a few seconds if you want to experiment and submit a pull request.

Ideally, the focus should be on #68 which would remove the need for the dialog. Feel free to submit pull requests to implement hierarchical sub-layouts. This might require working with the different framework vendors and format providers to include support for graph hierarchies or storing subgraph as functions. Flattened graphs with more than 1500 nodes (depending on connection patterns) will inherently test the limits of graph layout algorithms.

**Comment by fdwr** [comment]
I see, so most of the "loading time" is not actually loading time, but is rather layout time 🤔. I'm surprised because the layout for an ONNX model (with its top-down flow and unidirectionality) should be considerably simpler and relatively linear in time vs a general graph of arbitrary complex, but maybe the layout router (maybe GraphViz?) doesn't have a fast path for that case. Well, I always had the idea in the back of my mind to write a little C++ ONNX loader and viewer app for fun - maybe I can enjoy prototyping different faster layout algorithms :D...
