### ISSUE TITLE
netron stuck on 'Please update to the newest version'

### ISSUE THREAD

**Issue by maifeeulasad** [lutzroeder/netron#1164]
- Netron app and version: `6.5.9` 
- OS and browser version: `n/a` 

Steps to Reproduce:

1. Open any weight in older version with internet connection, and it keeps showing **Please update to the newest version**
![netron stuck on 'Please update to the newest version'](https://github.com/lutzroeder/netron/assets/29339330/2730c6e1-54b3-46b7-991c-68583ad3c905)

Please attach or link model files to reproduce the issue.
 - https://github.com/dDipankar/DeepGuide/blob/main/trained_deep_models/cas12a_seq_exp_purpose.h5
 - https://github.com/dDipankar/DeepGuide/blob/main/trained_deep_models/cas12a_wtt.h5
 - https://github.com/dDipankar/DeepGuide/blob/main/trained_deep_models/cas9_nu_wtt.h5
 - https://github.com/dDipankar/DeepGuide/blob/main/trained_deep_models/cas9_seq_wtt.h5

**Comment by lutzroeder** [comment]
@maifeeulasad can you provide some context why you need to continue using this old version?

**Comment by calad0i** [comment]
The annoying check happens around [source/browser.js#L58-L59](https://github.com/lutzroeder/netron/blob/09e53275f37c08613ab4344b00de886b663884be/source/browser.js#L58-L59). Simply purging them would fix it.

**Comment by Elvisass** [comment]
... and you can try giving a fake system time to it by "RunAsDate" tool

**Comment by SnoopJ** [comment]
I just learned about this behavior while using `netron` in an environment that is (for better or worse) lagging behind the leading edge of the greater Python ecosystem. We're still on Python 3.8, if that gives you a sense of the lag in this project's support window.

From the discussion above and the message presented to the user, I thought the software was making itself inoperable _because a new update is available_, but thanks to the reference to the specific check that does this, I am now burdened by the horrifying knowledge that _this software makes itself inoperable if the version you are running is 180 days or more past its release date_.

Please consider re-opening this issue and allowing those of us with ecosystems more constrained than you have imagined to continue using your otherwise excellent tool without undoing the self-harming code. Or at least document the rationale of this perplexingly anti-social check so that the _"WTF?"_ crowd can at least understand what purpose this serves to the project's maintenance.
