### ISSUE TITLE
Blank screen when loading large file

### ISSUE THREAD

**Issue by seanshpark** [lutzroeder/netron#1388]
- Netron app and version: 7.9.8 Desktop app
- OS and browser version: Windows 10

Steps to Reproduce:

1. Download [stable-diffusion-xl-base-1.0.zip](https://huggingface.co/presencesw/unet_onnx/blob/main/stable-diffusion-xl-base-1.0.zip) from https://huggingface.co/presencesw/unet_onnx/tree/main
2. Extract zip file; `model.onnx` and `mode.onnx_data` should be extracted. These file are about 10GB.
2. Open `model.onnx` file and wait
3. Netron App shows nothing

When I run from the `Command Prompt`, I see blow logs

> <--- Last few GCs --->
>
> [44784:000024CC00A50000]    39856 ms: Mark-Compact (reduce) 85.1 (105.8) -> 66.9 (85.9) MB, pooled: 0 MB, 118.33 / 0.04 ms  (+ 47.9 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1499 ms) (average mu = 0.994, cu[44784:000024CC00A50000]    43942 ms: Mark-Compact (reduce) 66.9 (85.9) -> 66.5 (71.6) MB, pooled: 0 MB, 1906.80 / 0.01 ms  (+ 56.2 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3443 ms) (average mu = 0.897, cu
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
 1: 00007FF670CE0336 node::SetTracingController+88134
 2: 00007FF670CE05A9 node::OnFatalError+585
 3: 00007FF67401FEC4 v8::Function::NewInstance+868
 4: 00007FF67401FE33 v8::Function::NewInstance+723
 5: 00007FF6740D03C7 v8::CppHeap::wrapper_descriptor+60423
 6: 00007FF6740E7E22 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+82338
 7: 00007FF66F6BA098 v8::CppHeap::CollectStatistics+99416
 8: 00007FF66F6C3429 v8::CppHeap::CollectStatistics+137193
 9: 00007FF66F6C3094 v8::CppHeap::CollectStatistics+136276
10: 00007FF66F928A85 cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlow+2757
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.

Hope to see some error message.

**Comment by lutzroeder** [comment]
@seanshpark please investigate and submit a pull request. This seems to also happen when loading the file without weights present so it's more likely a really large graph layout.

**Comment by beru** [comment]
This JavaScript heap out of memory happens when the chromium V8 engine tries to allocate more than 4GiB. This limitation comes from [Pointer Compression in V8](https://v8.dev/blog/pointer-compression).

With the `model.onnx`, the program crashes in `order` function while running a loop that calls `buildLayerGraph` function. [link](https://github.com/lutzroeder/netron/blob/9e75d13da320140cbba410ed13f077e39bf95b36/source/dagre.js#L1346-L1349)

There're several reasons why that much memory needs to be allocated by running the loop.
1. The loop needs to iterate 17022 times.
2. There're too many nodes and edges in the graph, 1590455 and 1595728. In this case, quite a lot of dummy nodes and edges are added in `normalize` function.

<details><summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/4d516825-bbbe-40ba-8110-5293919dd048)

</details>

I opened the model with Google AI Edge Model Explorer to check long edges. The input named `encoder_hidden_states` has a lot of connections to MatMul nodes.

<details><summary>screenshots</summary>

![image](https://github.com/user-attachments/assets/f34bbf7d-9352-43ba-a353-7ffecff7ed93)

![stable-diffusion-xl-base-1 0](https://github.com/user-attachments/assets/ce162b01-b874-4bb9-b206-0ffcd52c6fdf)

</details>

It seems to me that current Netron's layout algorithm avoids overlapping of connections lines and node rectangles at the cost of extra calculations and memory consumption. And that becomes problematic when there're a lot of extra long connection lines in models.
