### ISSUE TITLE
Would you draw background with gray or other color, Instead of white ? 

### ISSUE THREAD

**Issue by southsea0725** [lutzroeder/netron#229]
Would you draw background with gray or other color, Instead  @of white ?

**Comment by lutzroeder** [comment]
Is there a particular reason for gray instead of white or is this a personal preference? 

There are no plans to add color customization beyond what the OS is offering. On macOS and Safari Technology Preview, Netron will support system dark mode settings. electron/electron#15316 is tracking dark mode support for Windows and might be a good place for contributions.
