### ISSUE TITLE
Add option to turn off auto update

### ISSUE THREAD

**Issue by kice** [lutzroeder/netron#243]
Fast update is a nice thing, but since small update dose not make significant improvement, too many updates can be annoying. Would you like to add a option to disable checking update every time netron starts or only notify when a major update is avaiable (also with a manual "check for update" button)?

**Comment by lutzroeder** [comment]
How often do you think is a reasonable update rate? Also, have you considered using the [browser](https://www.lutzroeder.com/ai/netron) version?

**Comment by kice** [comment]
I think every two weeks will be reasonable unless there are some major changes happend. And it looks like the browser verion cannot export the graph to svg or png.

**Comment by lutzroeder** [comment]
See #163

`CommandOrControl+Shift+E` - Save as PNG
`CommandOrControl+Shift+Alt+E` - Save as SVG

**Comment by fdwr** [comment]
My goodness yes - my number one feature request for the stand-alone Netron would be to avoid the pop-up dialog every time I launch it, as I don't need the latest greatest (every 1 or 2 weeks would be fine). I click on "Remind me later", but it still pops up the next time just a few minutes later.

**Comment by bryanloz-xilinx** [comment]
Auto update breaks my functionality every time...

Please give us option to disable the update...

**Comment by ms2048** [comment]
at least disable updates on Windows 7, as there the newest version is not working, while the older ones worked ok

**Comment by wangchou** [comment]
Delete **app-update.yml**. Then, it won't auto update anymore.
![Screenshot 0005-07-03 at 14 22 17](https://github.com/lutzroeder/netron/assets/32716/3c3289f2-3d67-4575-93ba-0e898a3e184d)

**Comment by lutzroeder** [comment]
@bryanloz-xilinx can you open a new issue providing additional details.

**Comment by lutzroeder** [comment]
@ms2048 is switching to the browser version an option? See #1080

**Comment by fdwr** [comment]
@wangchou Thanks for the tip about the YAML file, but I don't want to *permanently* disable updates. I just want to have the very understandable control over *when* to update them. The way VS does it is commendable, showing a little notification bar at the top with a button to click to update, letting me click on my own terms rather than when I'm in the middle of a project. Netron though lately has this weird behavior of opening, fully loading the model (e.g. Stable Diffusion), and then just suddenly quitting (here I am scratching my head wondering if it crashed or what). I try to relaunch Netron, but it doesn't appear. Then a minute later, Netron resurrects, and I have to reload the huge model file again (which takes nearly a minute). Evidently what actually happened is that while I was in the middle of using it, Netron killed itself (or some background process killed it) to update itself. This has happened a few times the past few months.

**Comment by wangchou** [comment]
@fdwr I guess you can toggle automatic update on/off by renaming that file.

**Comment by lutzroeder** [comment]
@fdwr regarding auto-shutdown, which OS are you using, how did you install the app initially and do you remember which version this started happening?

**Comment by oxygen-dioxide** [comment]
> Fast update is a nice thing, but since small update dose not make significant improvement, too many updates can be annoying. Would you like to add a option to disable checking update every time netron starts or only notify when a major update is avaiable (also with a manual "check for update" button)?

You can Install netron with pip: `pip install netron` which won't update automatically

**Comment by lutzroeder** [comment]
Duplicate of #1514
