### ISSUE TITLE
Horizontal Layout

### ISSUE THREAD

**Issue by 80O** [lutzroeder/netron#248]
I'd be great if it is possible to plot the graph horizontally from left to right.

**Comment by lutzroeder** [comment]
Is there any specific reason or personal preference?

**Comment by febeks** [comment]
I suggest reopen this issue, it would be great to see it horizontaly, ie. for presentation reasons.

**Comment by lutzroeder** [comment]
Can you explain the presentation reasons? Argument so far has been that standardization is preferable over too many customization options that require folks to mentally adapt to different settings. Since the graphs tend to extend vertically, scroll wheel would be the favorable direction (#24). [issue248](https://github.com/lutzroeder/netron/tree/issue248) has a prototype to try out horizontal layout.

**Comment by febeks** [comment]
Scrolling is not the best view for displaying scheme on computer screen, since standard screen size is eg. 1920x1080 so more content can fit horizontaly. If I want to use vertical layout, I have to cut the scheme into pieces and stack them next to each other to be able to see all at once without scrolling. Left to right horizontal scheme would be very great, imo. Or maybe even combination of horizontal and vertical. Stack few boxes on top of each other, then move over to second column and continue stacking a few boxes, etc... Of course, last box in first column must be connected with first box in second column...

**Comment by lutzroeder** [comment]
This sounds like you are looking for a snake layout and not horizontal layout?

Have you tried the changes in the [issue248](https://github.com/lutzroeder/netron/tree/issue248)?

<img width="750" alt="1" src="https://user-images.githubusercontent.com/438516/57202322-cbe37f00-6f58-11e9-888a-858be8ce8c00.png">
<img width="750" alt="2" src="https://user-images.githubusercontent.com/438516/57202328-daca3180-6f58-11e9-988f-dd5d6b20512d.png">

**Comment by 80O** [comment]
I think an horizontal layout would be interesting for the following reasons:

- Read left to right, its more intuitive.
- Search google images for neural network, majority is from left to right.

I understand the choice for top to bottom, less space, can scroll easily.

I opened this issue as I was writing some documentation and without styling the image doesn't fit nicely inline resulting a page with just an image and no text whereas with a horizontal layout I could put text directly under it.

**Comment by jonese1234** [comment]
Just Tried v3.0.6 and this function is not there even though you pushed the code and updated the release version. The View drop down does not have the option and the shortcut "ctrl+T" does not work.

**Comment by vwxyzjn** [comment]
Just try the newest release. The shortcut "ctrl+T" does not work. It almost appears you reversed the commit on this issue...

**Comment by queequeq** [comment]
An option for horizontal layout would really be great. Netron is perfect to create both a simple plot for a presentation and a more detailed one for a report/paper. Especially for presentation purposes (we are talking 3:4 or, more likely, 16:9 format) a horizontal layout makes sense because it allows you to fit the complete graph on one slide.

**Comment by fenollp** [comment]
I +1'd the initial post, here's why:

I edit mediapipe graphs daily at $JOB and [their representation](https://viz.mediapipe.dev/demo/hair_segmentation) also shows graphs vertically (web version isn't open source, yet).
These are computation graphs and such graphs are very largely represented horizontally. See Unreal Engine, Fusion, MaxMSP, and definitely other industry-standard software editing solutions...
As mentioned above, many ML models are also represented horizontally (in papers at least).
Moreover, most screens are set up in paysage; only rarely in portrait mode :)

There are already 3+ toggelable display options, please pretty please add this one.
Netron is super neat & I just discovered its MediaPipe support (thanks!).
I would love to dive fully into this environment & actually build graphs from Netron (which I'm sure you've thought about)!

Do you have some escrow system we can use? I'm down to send you $100 to solve this issue.

**Comment by TechyNilesh** [comment]
In which version Horizontal Layout(snake layout) is present in on netron?? I did not find any options.

**Comment by wizcheu** [comment]
I‘m looking for the SNACK layout too...

**Comment by wangyexiang** [comment]
Dear sir, do you find the solution?@TechyNilesh

**Comment by TechyNilesh** [comment]
> Dear sir, do you find the solution?@TechyNilesh

No, I did not find any solution, If you get please share.

Actually This is very basic functionality, why there owner not providing??

**Comment by wangyexiang** [comment]
Dear sir, THX.@TechyNilesh
