### ISSUE TITLE
MXNet params support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#285]
The weights in a `-0000.params` file next to `-symbol.json` get loaded. Support`-XXXX.params` files and load the corresponding `-symbol.json` as well.

**Comment by nrupatunga** [comment]
In order to reproduce the issue, follow these steps
1. Download the model in the [link](https://www.dropbox.com/s/tj96fsm6t6rq8ye/model-r100-arcface-ms1m-refine-v2.zip?dl=0)
2. Extract the archive
3. Open [webapp-netron](https://lutzroeder.github.io/netron/) and load model-symbol.json. Note that model-0000.params is there in the same folder. 
4. When you click on convolution layer below is what you see, (tensor is empty on the corresponding weights). 

![mxnet-netron](https://user-images.githubusercontent.com/980580/59407268-5fb53000-8dce-11e9-9b30-046114852048.png)

Hope this helps, Let me know if you need more information.

**Comment by lutzroeder** [comment]
Yes, that is a browser limitation. The website can't access other files that are local on disk. It would require some changes to open both files in the same dialog (which isn't intuitive and hard to discover). Can you try the desktop version or Python server instead?

**Comment by nrupatunga** [comment]
Yes, that perfectly makes sense. Should have thought about it. And thank you for the help. It works now.

**Comment by lutzroeder** [comment]
The browser version also supports opening `.params` and `-symbol.json` if they are in a single `zip` file.

**Comment by lutzroeder** [comment]
The browser version now supports dragging and opening both files via drag & drop or the file dialog.

**Comment by nazsw** [comment]
Hi @lutzroeder . The app is great for visualization of the tree - thank you. Are you planning on adding the weights exporting feature? I tried using properties window and saving weights manually for each layer, but going through 100+ layers simply sucks. It would be nice to have global "save" button for weights and biases similar to one you have for each layer.
