### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#563]
Please provide steps or model files to reproduce this issue.

**Comment by steven0129** [comment]
Same Issue

**Comment by lutzroeder** [comment]
@steven0129 can you share the model file to reproduce the issue?

**Comment by steven0129** [comment]
@lutzroeder The problem seems to have been gone for now.

**Comment by TomWildenhain-Microsoft** [comment]
model.json from:
https://tfhub.dev/tensorflow/tfjs-model/posenet/mobilenet/float/075/1/default/1 
will reproduce (expand the filter weight of the first conv)

![image](https://user-images.githubusercontent.com/67606533/134069827-62f00d83-8083-4b80-914f-815835318322.png)

**Comment by lutzroeder** [comment]
@TomWildenhain-Microsoft this seems to be a corrupt model file. After extracting `posenet_mobilenet_float_075_1_default_1.tar` all files are compressed in Gzip format even though the file extensions suggest otherwise. Can you clarify this with the model author?

**Comment by TomWildenhain-Microsoft** [comment]
Yep the weights are gzip compressed.  There are actually a lot of tfjs models on tfhub with gzip compression, even on .json files.  I didn't make the model. I have no idea why Google likes to do it this way.  It's fine with me if Netron doesn't handle these ones, just posting since the dialog box requested it.
