### ISSUE TITLE
Model comparison support

### ISSUE THREAD

**Issue by Vozf** [lutzroeder/netron#705]
It would be useful to compare 2 graphs to find the difference between the two. 
It can be possibly viewed as 2 side by side graphs with duplicated navigation where same nodes are highlighted as green and different nodes are highlighted as yellow

**Comment by lutzroeder** [comment]
@Vozf please implement this an submit a pull request.

**Comment by drewm1980** [comment]
Graph comparison is NP-hard, but I doubt it matters because convnet graphs are small: https://en.wikipedia.org/wiki/Graph_isomorphism_problem

It's only one of many challenges to building a tool like this, but graph isomorphism / matching is present in graph libaries, e.g. 

https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.isomorphism.is_isomorphic.html#networkx.algorithms.isomorphism.is_isomorphic

Anyone know any precedents for convnet model comparison tools? It's a bit tough to search on; vast majority of hits are for experimental comparisons of known ~different architectures.
