### ISSUE TITLE
v4.8.3, open model very slow: need to accept cookies usage for each open.

### ISSUE THREAD

**Issue by luchangli03** [lutzroeder/netron#706]
v4.8.3, open model very slow: need to accept cookies usage for each open.

**Comment by lutzroeder** [comment]
@luchangli03 can you provide some context or investigate why this is happening? Which bowser and OS or how the model is loaded. Does it happen for all files and formats or only specific ones?

**Comment by luchangli03** [comment]
> @luchangli03 can you provide some context or investigate why this is happening? Which bowser and OS or how the model is loaded. Does it happen for all files and formats or only specific ones?

I double-click the pb or pbtxt model to open the netron after installing Netron-Setup-4.8.3.exe on win10. For older versions, I only need to accept the usage of cookies at the usage after installation. But now I need to wait about half minute for each model open no matter how large the model is.

**Comment by lutzroeder** [comment]
@luchangli03 can you follow the instructions in [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/main/DEVELOPMENT.md) and debug this on your machine.
1) Drag and drop make a difference instead of double-click
2) `%APPDATA$\Netron\configuration.json` or `%APPDATA$\Electron\configuration.json` exists and is accessible
3) `configuration.json` contains a `consent` field
4) The initialize code in `electron.js` running in the Renderer process

**Comment by lutzroeder** [comment]
@ypwhs please [investigate](https://github.com/lutzroeder/netron/blob/main/DEVELOPMENT.md) why this is happening and submit a fix.
