### ISSUE TITLE
Shortcut to reload model in current window

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/Netron#78]

**Comment by skrishnanv** [comment]
Hello,
First, Thanks for Netron. 
as mentioned in this topic, i am trying to reload/refresh an already loaded file. i am using a local server. i dont know javascript so i am not sure what is the change mentioned in this issue resolution. Since it is marked as closed, i assume that reloading the same model is possible without going to the "open file" dialogue. i am trying to reload the model using F5 button(google chrome on Windows). Unfortunately, i am getting the netron homepage and not the refreshed model. Please let me know if i am doing something wrong. Version 7.4.4.
thank you.

**Comment by lutzroeder** [comment]
@skrishnanv this change applies to the desktop app. In the browser version only models added via `?url=` can be reloaded. The browser does not have direct access to the local disk, loading requires permission through the file open dialog.

**Comment by skrishnanv** [comment]
Hello,
thanks for your super fast reply. apologise for my lack of browser knowledge and it is clearer now. to make sure i understand correctly, models added via `?url=` means that models are somehow loaded via a URL. would that be right?
unfortunately, i am not able able to install the desktop exe due to lack of permissions on corporate laptop; so i think the only way for me is to reopen the file. this is not a bad option; just want to confirm this is the only possibility.
as again, thank you.
